(function(){
  const METRIKA_ID=111504350,CONSENT_KEY='site_cookie_choice',SCRIPT_SRC='https://mc.yandex.ru/metrika/tag.js?id=111504350';
  const READ_GOALS=[{percent:25,id:'read_25'},{percent:50,id:'read_50'},{percent:75,id:'read_75'},{percent:90,id:'read_90'}];
  function installOphthalmologyEventsPatch(){
    if(!/\/for-doctors\/events\/?$/.test(location.pathname)||typeof fetch!=='function'||window.__ophEventsPatchInstalled)return;
    window.__ophEventsPatchInstalled=true;const originalFetch=fetch.bind(window),verified='2026-08-31';
    const common=[
      ['ciob-2026','CIOB 2026','Cumbre de Innovación Oftalmológica del Biobío 2026','CIOB','2026-10-02','2026-10-03','Concepción','Chile','Latin America','Centro de Eventos Mitrinco, Concepción',['Cataract / IOL','Cornea','Retina','Glaucoma','Research','AI / management'],'https://www.ciob.cl/'],
      ['bolivia-ophthalmology-2026','XXXI Bolivian Congress of Ophthalmology 2026','XXXI Congreso Boliviano de Oftalmología “Dra. Rosario García”','Sociedad Boliviana de Oftalmología','2026-10-22','2026-10-24','Santa Cruz de la Sierra','Bolivia','Latin America','Hotel Los Tajibos, Santa Cruz',['Cataract / IOL','Cornea','Retina','Glaucoma','Paediatric ophthalmology','Strabismus','Research'],'https://cboftalmologia2026.com/'],
      ['sprv-gladaof-2026','SPRV 2026 · GLADAOF','11th Congress of the Pan-American Society of Retina and Vitreous & 20th GLADAOF Forum','Pan-American Society of Retina and Vitreous / GLADAOF','2026-10-29','2026-11-01','São Paulo','Brazil','Latin America','Grand Hyatt, São Paulo',['Retina','Research'],'https://sprv2026.com/'],
      ['bascom-palmer-curso-2026','Bascom Palmer CURSO 2026','XLVIII Bascom Palmer InterAmerican Course in Clinical Ophthalmology 2026','Bascom Palmer Eye Institute','2026-11-01','2026-11-04','Miami','USA','North America','Hyatt Regency Miami Downtown',['Cataract / IOL','Refractive','Cornea','Retina','Glaucoma','Inflammation','Paediatric ophthalmology','Strabismus','Neuro-ophthalmology','Oculoplastics'],'https://umiamihealth.org/bascom-palmer-eye-institute/healthcare-professionals/continuing-medical-education/xlviii-inter-american-course-in-clinical-ophthalmology'],
      ['isa-2026','XVI ISA Meeting','XVI International Strabismological Association Meeting','International Strabismological Association','2026-11-11','2026-11-14','Buenos Aires','Argentina','Latin America','Auditorios UCA – Edificio San José',['Strabismus','Paediatric ophthalmology','Research'],'https://isa2026.com.ar/'],
      ['aacgc-2027','AACGC 2027 · Indonesian National Glaucoma Meeting','18th Asian Angle-Closure Glaucoma Club Meeting in Conjunction With the 11th Indonesian National Glaucoma Meeting','Asian Angle-Closure Glaucoma Club / Indonesian National Glaucoma Meeting','2027-10-15','2027-10-16','Jakarta','Indonesia','Asia–Pacific','Jakarta, Indonesia',['Glaucoma','Research'],'https://apaophth.org/congress/calendar/'],
      ['alaccsa-2026','XXVI ALACCSA-R International Congress 2026','XXVI Congreso Internacional ALACCSA-R 2026','ALACCSA-R','2026-10-22','2026-10-24','Asunción','Paraguay','Latin America','Hotel Sheraton, Asunción',['Cataract / IOL','Refractive','Cornea','Research'],'https://alaccsa.com/'],
      ['trends-retina-2026','Trends in Retina 2026','6th Trends in Retina 2026','IMO Grupo Miranza','2026-11-12','2026-11-14','Barcelona','Spain','Europe','Convention Center of IMO Grupo Miranza Barcelona',['Retina','Research'],'https://miranza.es/en/tir-2026/'],
      ['asia-cornea-2026','Asia Cornea Society 2026','10th Asia Cornea Society Biennial Scientific Meeting','Asia Cornea Society','2026-11-27','2026-11-29','Hong Kong','China','Greater China','Hong Kong',['Cornea','Research'],'https://www.asiacorneasociety.org/'],
      ['paao-2027','PAAO 2027','XXXVII Pan-American Congress of Ophthalmology','Pan-American Association of Ophthalmology','2027-03-17','2027-03-20','Lima','Peru','Latin America','Lima Convention Center',['Cataract / IOL','Refractive','Cornea','Retina','Glaucoma','Inflammation','Paediatric ophthalmology','Strabismus','Neuro-ophthalmology','Oculoplastics','Research'],'https://paao.org/'],
      ['apspos-capos-2027','APSPOS/CAPOS 2027','4th Asia-Pacific Strabismus and Paediatric Ophthalmology Society Congress with CAPOS','APSPOS / CAPOS','2027-04-15','2027-04-17','Tianjin','China','Greater China','Tianjin, China',['Paediatric ophthalmology','Strabismus','Research'],'https://apaophth.org/congress/calendar/'],
      ['wgc-2027','World Glaucoma Congress 2027','12th World Glaucoma Congress','World Glaucoma Association','2027-04-20','2027-04-23','Kyoto','Japan','Asia–Pacific','Kyoto International Conference Center',['Glaucoma','Research'],'https://worldglaucomacongress.org/'],
      ['soe-2027','SOE 2027','European Society of Ophthalmology Congress 2027','European Society of Ophthalmology','2027-06-18','2027-06-20','Athens','Greece','Europe','Athens, Greece',['Cataract / IOL','Cornea','Retina','Glaucoma','Paediatric ophthalmology','Neuro-ophthalmology','Oculoplastics','Research'],'https://soevision.org/']
    ];
    function make(x,en){let [id,title,fullTitle,org,start,end,city,country,region,venue,categories,official]=x;if(!en){const map={'Latin America':'Латинская Америка','North America':'Северная Америка','Asia–Pacific':'Азия–Тихоокеанский','Greater China':'Китай / Greater China','Europe':'Европа',Chile:'Чили',Bolivia:'Боливия',Brazil:'Бразилия',USA:'США',Argentina:'Аргентина',Indonesia:'Индонезия',Paraguay:'Парагвай',Spain:'Испания',China:'Китай',Japan:'Япония',Peru:'Перу',Greece:'Греция',Miami:'Майами',Jakarta:'Джакарта',Barcelona:'Барселона',Kyoto:'Киото',Athens:'Афины',Lima:'Лима','Santa Cruz de la Sierra':'Санта-Крус-де-ла-Сьерра'};city=map[city]||city;country=map[country]||country;region=map[region]||region;categories=categories.map(c=>({'Cataract / IOL':'Катаракта / ИОЛ',Refractive:'Рефракция',Cornea:'Роговица',Glaucoma:'Глаукома',Inflammation:'Воспаление','Paediatric ophthalmology':'Детская офтальмология',Strabismus:'Страбизм','Neuro-ophthalmology':'Нейроофтальмология',Oculoplastics:'Окулопластика','AI / management':'AI / управление'}[c]||c));}
      const e={id,featured:['bolivia-ophthalmology-2026','sprv-gladaof-2026','bascom-palmer-curso-2026','isa-2026','trends-retina-2026','paao-2027','wgc-2027'].includes(id),level:'specialty',title,fullTitle,org,start,end,city,country,region,mode:en?'In person':'Очно',venue,categories,credits:en?'CME/CPD: check with organiser':'CME/НМО: уточняется организатором',submissionOpen:false,official,program:official,registration:official,submit:null,verified,description:en?'International ophthalmology meeting verified against the organiser or official society calendar.':'Международное офтальмологическое мероприятие, проверенное по сайту организатора или официальному календарю общества.',deadlines:[]};
      if(id==='bolivia-ophthalmology-2026'){e.submissionOpen=true;e.submit='https://cboftalmologia2026.com/trabajos.html';e.deadlines=[{kind:'abstract',label:en?'Scientific work submission':'Подача научных работ',date:'2026-08-30T23:00:00-04:00',timeKnown:true,zone:'BOT',url:e.submit,note:en?'Official deadline: 30 August 2026, 23:00 local time.':'Официальный срок: 30 августа 2026, 23:00 по местному времени.'}]}
      if(id==='trends-retina-2026')e.deadlines=[{kind:'registration',label:en?'Early registration':'Ранняя регистрация',date:'2026-09-15',timeKnown:false,zone:'Europe/Madrid',url:official,note:en?'Early fee applies before 15 September 2026.':'Льготный регистрационный тариф действует до 15 сентября 2026.'}];
      if(id==='asia-cornea-2026')e.deadlines=[{kind:'registration',label:en?'Advance registration':'Предварительная регистрация',date:'2026-11-26',timeKnown:false,zone:'Asia/Hong_Kong',url:official,note:en?'Advance registration available through 26 November 2026.':'Предварительная регистрация доступна до 26 ноября 2026.'}];
      if(id==='paao-2027'){e.submissionOpen=true;e.submit=official;e.deadlines=[{kind:'registration',label:en?'Early-bird registration':'Early-bird регистрация',date:'2026-10-15',timeKnown:false,zone:'America/Lima',url:official,note:en?'Early-bird registration closes 15 October 2026.':'Льготная регистрация до 15 октября 2026.'}]}
      if(id==='apspos-capos-2027'){e.submissionOpen=true;e.submit=official;e.deadlines=[{kind:'abstract',label:en?'Abstract submission':'Подача тезисов',date:'2026-12-01T23:59:00+08:00',timeKnown:true,zone:'UTC+8',url:official,note:en?'Abstract deadline: 1 December 2026, 23:59 UTC+8.':'Дедлайн тезисов: 1 декабря 2026, 23:59 UTC+8.'}]}
      if(id==='wgc-2027'){e.submissionOpen=true;e.submit='https://worldglaucomacongress.org/';e.deadlines=[{kind:'abstract',label:en?'Abstract submission':'Подача тезисов',date:'2026-10-19T23:59:00+02:00',timeKnown:true,zone:'CEST',url:e.submit,note:en?'Abstract deadline: 19 October 2026.':'Дедлайн тезисов: 19 октября 2026.'},{kind:'upload',label:en?'Film Festival submission':'Подача в Film Festival',date:'2026-10-19T23:59:00+02:00',timeKnown:true,zone:'CEST',url:e.submit,note:en?'Film Festival deadline matches the abstract deadline.':'Film Festival принимает материалы до того же срока.'},{kind:'registration',label:en?'Early-bird registration':'Early-bird регистрация',date:'2027-01-18',timeKnown:false,zone:'Europe/Amsterdam',url:e.registration,note:''},{kind:'registration',label:en?'Regular registration':'Обычная регистрация',date:'2027-03-15',timeKnown:false,zone:'Europe/Amsterdam',url:e.registration,note:''}]}
      return e;
    }
    window.fetch=async function(input,init){const response=await originalFetch(input,init);let url='';try{url=typeof input==='string'?input:(input&&input.url)||''}catch(_){}if(!/ophthalmology-events\.(ru|en)\.json(?:[?#].*)?$/.test(url)||!response.ok)return response;try{const data=await response.clone().json(),en=/\.en\.json/.test(url),patch=common.map(x=>make(x,en)),byId=new Map((data.events||[]).map(e=>[e.id,e]));patch.forEach(e=>byId.set(e.id,{...(byId.get(e.id)||{}),...e}));for(const [id,e] of byId){const name=(e.title||'')+' '+(e.fullTitle||'');if(/APAO 2027/i.test(name)){e.submissionOpen=true;e.submit='https://2027.apaophth.org/abstract-submission/';e.verified=verified;e.deadlines=(e.deadlines||[]).filter(d=>d.kind!=='abstract'&&d.kind!=='grant');e.deadlines.push({kind:'abstract',label:en?'Abstract submission':'Подача тезисов',date:'2026-09-16T23:59:00+08:00',timeKnown:true,zone:'GMT+8',url:e.submit,note:en?'Deadline extended to 16 September 2026.':'Дедлайн продлён до 16 сентября 2026.'},{kind:'grant',label:en?'Travel grants':'Travel grants',date:'2026-09-30',timeKnown:false,zone:'GMT+8',url:'https://apaophth.org/latest-news/',note:en?'Travel grant applications close 30 September 2026.':'Приём заявок на travel grants до 30 сентября 2026.'});byId.set(id,e)}if(/ARVO 2027/i.test(name)){e.start='2027-05-02';e.end='2027-05-06';e.city=en?'San Diego':'Сан-Диего';e.country=en?'USA':'США';e.region=en?'North America':'Северная Америка';e.venue='San Diego Convention Center';e.submissionOpen=false;e.official='https://www.arvo.org/annual-meeting/';e.registration=e.official;e.submit='https://www.arvo.org/annual-meeting/';e.credits=en?'CME available':'CME доступно';e.verified=verified;e.submissionNote=en?'Abstract submission opens 16 October 2026.':'Подача тезисов откроется 16 октября 2026.';e.deadlines=(e.deadlines||[]).filter(d=>!['abstract','registration','grant'].includes(d.kind));e.deadlines.push({kind:'abstract',label:en?'Abstract submission deadline':'Дедлайн подачи тезисов',date:'2026-12-04T17:00:00-05:00',timeKnown:true,zone:'EST',url:e.submit,note:en?'Abstract submission opens 16 October 2026.':'Подача тезисов открывается 16 октября 2026.'},{kind:'registration',label:en?'Early registration':'Ранняя регистрация',date:'2027-03-10',timeKnown:false,zone:'America/Los_Angeles',url:e.registration,note:en?'Early registration is open.':'Ранняя регистрация открыта.'},{kind:'grant',label:en?'Travel grants':'Travel grants',date:'2026-12-04T17:00:00-05:00',timeKnown:true,zone:'EST',url:e.official,note:en?'Travel grants are available for eligible early-career researchers.':'Доступны travel grants для соответствующих критериям молодых исследователей.'});byId.set(id,e)}}data.events=[...byId.values()];data.verifiedAt=verified;data.generatedAt='2026-08-31T13:49:00+03:00';return new Response(JSON.stringify(data),{status:response.status,statusText:response.statusText,headers:{'Content-Type':'application/json; charset=utf-8'}})}catch(_){return response}};
  }
  installOphthalmologyEventsPatch();
  let trackingBound=false,readingFramePending=false;const reachedReadGoals=new Set();
  function hasAnalyticsConsent(){try{return localStorage.getItem(CONSENT_KEY)==='analytics'}catch(_){return false}}
  function sendGoal(target){if(!hasAnalyticsConsent()||typeof window.ym!=='function')return false;window.ym(METRIKA_ID,'reachGoal',target);return true}
  function initSiteAnalytics(){if(window.__siteAnalyticsInitialized||!hasAnalyticsConsent())return;window.__siteAnalyticsInitialized=true;(function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};m[i].l=1*new Date();for(let j=0;j<e.scripts.length;j++){if(e.scripts[j].src===r)return}k=e.createElement(t);a=e.getElementsByTagName(t)[0];k.async=1;k.src=r;a.parentNode.insertBefore(k,a)})(window,document,'script',SCRIPT_SRC,'ym');window.ym(METRIKA_ID,'init',{ssr:true,webvisor:true,clickmap:true,ecommerce:'dataLayer',referrer:document.referrer,url:location.href,accurateTrackBounce:true,trackLinks:true})}
  function safeUrl(link){try{return new URL(link.href,location.href)}catch(_){return null}}
  function handleDocumentClick(event){const target=event.target;if(!target||typeof target.closest!=='function')return;const summary=target.closest('summary');if(summary){const details=summary.closest('details');setTimeout(()=>{if(details&&details.open)sendGoal('faq_open')},0)}const link=target.closest('a');if(!link)return;const u=safeUrl(link),host=u?u.hostname.toLowerCase():'';if(host==='t.me'||host==='telegram.me'||host.endsWith('.telegram.me'))sendGoal('telegram_click');if(host==='prodoctorov.ru'||host.endsWith('.prodoctorov.ru'))sendGoal('prodoctorov_click');const label=(link.textContent||'').replace(/\s+/g,' ').trim().toLowerCase();if(link.matches('[data-analytics-cta], .button.primary, .cta, .cta-button, .contact-button')||/запис|консультац|написать лично|write personally|book appointment|make an appointment/.test(label))sendGoal('cta_click')}
  function handleSearchInput(event){const t=event.target;if(!t||!t.matches||!t.matches('input[type="search"]')||!String(t.value||'').trim()||t.dataset.analyticsSearchTracked==='1')return;if(sendGoal('search_use'))t.dataset.analyticsSearchTracked='1'}
  function readingPercent(){const m=document.getElementById('content-material')||document.querySelector('main');if(!m||!m.getBoundingClientRect)return 0;const r=m.getBoundingClientRect(),y=scrollY||pageYOffset||0,h=innerHeight||document.documentElement.clientHeight||0;return Math.max(0,Math.min(100,((y+h-(r.top+y))/Math.max(r.height||m.offsetHeight||0,1))*100))}
  function trackReadingProgress(){const p=readingPercent();for(const g of READ_GOALS)if(p>=g.percent&&!reachedReadGoals.has(g.id)&&sendGoal(g.id))reachedReadGoals.add(g.id)}
  function scheduleReadingProgress(){if(readingFramePending)return;readingFramePending=true;(requestAnimationFrame||function(fn){setTimeout(fn,0)})(()=>{readingFramePending=false;trackReadingProgress()})}
  function bindInteractionTracking(){if(trackingBound)return;trackingBound=true;document.addEventListener('click',handleDocumentClick);document.addEventListener('input',handleSearchInput);addEventListener('scroll',scheduleReadingProgress,{passive:true});addEventListener('resize',scheduleReadingProgress);scheduleReadingProgress()}
  window.initSiteAnalytics=initSiteAnalytics;addEventListener('site:analytics-consent',()=>{initSiteAnalytics();scheduleReadingProgress()});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bindInteractionTracking);else bindInteractionTracking();if(hasAnalyticsConsent())initSiteAnalytics();
})();