#!/usr/bin/env python3
import json
from datetime import datetime, timezone
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; DATA=ROOT/'assets/data'; V='2026-08-16'

def loc(ru,en): return {'ru':ru,'en':en}
def event(id,title,full,org,start,end,city,country,region,venue,cats,official,desc,level='specialty',featured=False,deadlines=None,submission=False,submit=None,registration=None):
    return {'id':id,'featured':featured,'level':level,'title':title,'fullTitle':full,'org':org,'start':start,'end':end,'city':city,'country':country,'region':region,'mode':loc('Очно','In person'),'venue':venue,'categories':cats,'credits':loc('CME/НМО: уточняется организатором','CME/CPD: check with organiser'),'submissionOpen':submission,'official':official,'program':official,'registration':registration or official,'submit':submit,'verified':V,'description':desc,'deadlines':deadlines or []}
def deadline(kind,label,date,url,zone='',time=False,note=None):
    d={'kind':kind,'label':label,'date':date,'timeKnown':time,'zone':zone,'url':url}
    if note:d['note']=note
    return d
E=[
event('iser-2026',loc('ISER 2026','ISER 2026'),loc('XXVII Biennial Meeting of the International Society for Eye Research','XXVII Biennial Meeting of the International Society for Eye Research'),loc('International Society for Eye Research','International Society for Eye Research'),'2026-08-23','2026-08-27',loc('Валенсия','Valencia'),loc('Испания','Spain'),loc('Европа','Europe'),loc('Валенсия, Испания','Valencia, Spain'),loc(['Research','Retina','Роговица','Глаукома'],['Research','Retina','Cornea','Glaucoma']),'https://iser.org/page/Events_Schedule',loc('Международная биеннале по экспериментальной и трансляционной офтальмологии и науке о зрении.','International biennial meeting focused on experimental and translational eye and vision research.'),level='research',featured=True),
event('retina-society-2026',loc('Retina Society 2026','Retina Society 2026'),loc('59th Annual Scientific Meeting of The Retina Society','59th Annual Scientific Meeting of The Retina Society'),loc('The Retina Society','The Retina Society'),'2026-09-23','2026-09-26',loc('Лос-Анджелес','Los Angeles'),loc('США','USA'),loc('Северная Америка','North America'),loc('Fairmont Century Plaza, Los Angeles','Fairmont Century Plaza, Los Angeles'),loc(['Retina','Research'],['Retina','Research']),'https://www.retinasociety.org/page/2/annual-meeting',loc('59-я научная встреча Retina Society, посвящённая последним достижениям медицинской и хирургической ретины.','The Retina Society’s 59th scientific meeting, focused on advances in medical and surgical retina.'),featured=True,registration='https://www.retinasociety.org/page/2/annual-meeting'),
event('cornea-eye-banking-2026',loc('Cornea & Eye Banking Forum 2026','Cornea & Eye Banking Forum 2026'),loc('Cornea and Eye Banking Forum 2026','Cornea and Eye Banking Forum 2026'),loc('Cornea Society · Eye Bank Association of America','Cornea Society · Eye Bank Association of America'),'2026-10-09','2026-10-09',loc('Новый Орлеан','New Orleans'),loc('США','USA'),loc('Северная Америка','North America'),loc('New Orleans, Louisiana','New Orleans, Louisiana'),loc(['Роговица','Research'],['Cornea','Research']),'https://corneasociety.org/cornea-and-eye-banking-forum',loc('Ежегодный форум Cornea Society и eye banking community, проходящий непосредственно перед AAO.','Annual Cornea Society and eye-banking forum held immediately before the AAO meeting.')),
event('ags-2027',loc('AGS 2027','AGS 2027'),loc('American Glaucoma Society 2027 Annual Meeting','American Glaucoma Society 2027 Annual Meeting'),loc('American Glaucoma Society','American Glaucoma Society'),'2027-03-04','2027-03-07',loc('Тусон','Tucson'),loc('США','USA'),loc('Северная Америка','North America'),loc('JW Marriott Starr Pass, Tucson, Arizona','JW Marriott Starr Pass, Tucson, Arizona'),loc(['Глаукома','Research'],['Glaucoma','Research']),'https://www.americanglaucomasociety.net/events/event-description?CalendarEventKey=64f2cced-b152-4572-abfa-019b70385b30&Home=%2Fevents%2Fcalendar',loc('Ежегодная специализированная встреча American Glaucoma Society по диагностике, хирургии и исследованиям глаукомы.','American Glaucoma Society annual specialist meeting covering glaucoma diagnosis, surgery and research.'),featured=True),
event('fuji-retina-2027',loc('FujiRetina 2027','FujiRetina 2027'),loc('6th FujiRetina International Meeting','6th FujiRetina International Meeting'),loc('FujiRetina · Japan Retina and Vitreous Society','FujiRetina · Japan Retina and Vitreous Society'),'2027-03-26','2027-03-28',loc('Токио','Tokyo'),loc('Япония','Japan'),loc('Азия–Тихоокеанский','Asia–Pacific'),loc('Toranomon Hills Forum, Tokyo','Toranomon Hills Forum, Tokyo'),loc(['Retina','Research','AI / управление'],['Retina','Research','AI / management']),'https://convention.jtbcom.co.jp/fujiretina/information/index.html',loc('Международная витреоретинальная встреча в Токио, ассоциированная с Japanese Retina and Vitreous Society; официальный язык — английский.','International vitreoretinal meeting in Tokyo in association with the Japanese Retina and Vitreous Society; the official language is English.'),featured=True),
event('wcpos-vi-2027',loc('WCPOS VI 2027','WCPOS VI 2027'),loc('6th World Congress of Paediatric Ophthalmology & Strabismus','6th World Congress of Paediatric Ophthalmology & Strabismus'),loc('World Society of Paediatric Ophthalmology and Strabismus','World Society of Paediatric Ophthalmology and Strabismus'),'2027-05-13','2027-05-15',loc('Канкун','Cancun'),loc('Мексика','Mexico'),loc('Латинская Америка','Latin America'),loc('Cancun, Mexico','Cancun, Mexico'),loc(['Детская офтальмология','Страбизм','Research'],['Pediatric ophthalmology','Strabismus','Research']),'https://wspos.org/wcpos-vi/',loc('Шестой всемирный конгресс WSPOS по детской офтальмологии и страбизмологии.','The sixth WSPOS world congress in paediatric ophthalmology and strabismus.'),level='major',featured=True,submit='https://wspos.org/wcpos-vi/'),
event('macula-society-2027',loc('Macula Society 50th Annual Meeting','Macula Society 50th Annual Meeting'),loc('50th Anniversary Annual Meeting of The Macula Society','50th Anniversary Annual Meeting of The Macula Society'),loc('The Macula Society','The Macula Society'),'2027-06-09','2027-06-12',loc('Канны','Cannes'),loc('Франция','France'),loc('Европа','Europe'),loc('Carlton Cannes, Cannes','Carlton Cannes, Cannes'),loc(['Retina','Research'],['Retina','Research']),'https://www.maculasociety.org/50th-anniversary/',loc('Юбилейная 50-я научная встреча Macula Society в Каннах, посвящённая заболеваниям макулы и ретинальной науке.','The Macula Society’s 50th anniversary scientific meeting in Cannes, focused on macular disease and retinal research.'),featured=True,deadlines=[deadline('registration',loc('Открытие регистрации','Registration opens'),'2026-09-14','https://www.maculasociety.org/49th-annual-meeting/','Europe/Paris',False)]),
event('retina-society-2027',loc('Retina Society 2027','Retina Society 2027'),loc('60th Annual Meeting of The Retina Society','60th Annual Meeting of The Retina Society'),loc('The Retina Society','The Retina Society'),'2027-10-20','2027-10-23',loc('Бостон','Boston'),loc('США','USA'),loc('Северная Америка','North America'),loc('OMNI Boston at the Seaport','OMNI Boston at the Seaport'),loc(['Retina','Research'],['Retina','Research']),'https://www.retinasociety.org/page/17/future-annual-meetings',loc('60-я юбилейная ежегодная встреча Retina Society в Бостоне.','The Retina Society’s 60th annual meeting in Boston.'),featured=False),
event('aao-2027',loc('AAO 2027','AAO 2027'),loc('American Academy of Ophthalmology Annual Meeting 2027','American Academy of Ophthalmology Annual Meeting 2027'),loc('American Academy of Ophthalmology','American Academy of Ophthalmology'),'2027-11-12','2027-11-15',loc('Лас-Вегас','Las Vegas'),loc('США','USA'),loc('Северная Америка','North America'),loc('Las Vegas, Nevada','Las Vegas, Nevada'),loc(['Катаракта / ИОЛ','Рефракция','Роговица','Retina','Глаукома','Воспаление','Детская офтальмология','Страбизм','Нейроофтальмология','Окулопластика'],['Cataract / IOL','Refractive','Cornea','Retina','Glaucoma','Inflammation','Pediatric ophthalmology','Strabismus','Neuro-ophthalmology','Oculoplastics']),'https://apaophth.org/congress/calendar/',loc('Подтверждённая календарём APAO будущая ежегодная встреча American Academy of Ophthalmology в Лас-Вегасе.','Future American Academy of Ophthalmology annual meeting in Las Vegas, confirmed on the APAO meeting calendar.'),level='major')]

def pick(v,lang):
    if isinstance(v,dict) and set(v)<= {'ru','en'}: return pick(v[lang],lang)
    if isinstance(v,dict): return {k:pick(x,lang) for k,x in v.items()}
    if isinstance(v,list): return [pick(x,lang) for x in v]
    return v
for lang in ('ru','en'):
    p=DATA/f'ophthalmology-events.{lang}.json'; x=json.loads(p.read_text(encoding='utf-8')); by={e['id']:e for e in x['events']}
    for e in E: by[e['id']]=pick(e,lang)
    x['events']=sorted(by.values(),key=lambda e:(e['start'],e['id'])); x['generatedAt']=datetime.now(timezone.utc).isoformat(timespec='seconds'); p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
sources=[
('iser-extra','https://iser.org/page/Events_Schedule',['iser-2026'],['August 23-27, 2026','Valencia']),
('retina-society-extra','https://www.retinasociety.org/page/2/annual-meeting',['retina-society-2026'],['September 23-26, 2026','Los Angeles']),
('cornea-forum-extra','https://corneasociety.org/cornea-and-eye-banking-forum',['cornea-eye-banking-2026'],['October 09, 2026','New Orleans']),
('ags-extra','https://www.americanglaucomasociety.net/go.aspx?c=emcalendar',['ags-2027'],['Mar 4, 2027','Tucson']),
('fuji-extra','https://convention.jtbcom.co.jp/fujiretina/information/index.html',['fuji-retina-2027'],['March 26','2027']),
('wspos-extra','https://wspos.org/wcpos-vi/',['wcpos-vi-2027'],['May 13','May 15 2027']),
('macula-extra','https://www.maculasociety.org/50th-anniversary/',['macula-society-2027'],['June 9','12, 2027']),
('retina-future-extra','https://www.retinasociety.org/page/17/future-annual-meetings',['retina-society-2027'],['October 20-23, 2027','Boston']),
('aao-future-extra','https://apaophth.org/congress/calendar/',['aao-2027'],['AAO 2027','November 12-15, 2027'])]
p=DATA/'ophthalmology-event-sources.json'; x=json.loads(p.read_text(encoding='utf-8')); by={s['id']:s for s in x['sources']}
for sid,url,ids,terms in sources: by[sid]={'id':sid,'official':True,'url':url,'eventIds':ids,'watchTerms':terms}
x['sources']=sorted(by.values(),key=lambda s:s['id']); p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print('added',len(E),'events')
