#!/usr/bin/env python3
from __future__ import annotations
import json, re
from datetime import datetime, timezone
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
DATA=ROOT/'assets/data'
VERIFIED='2026-08-16'

def bi(ru,en): return {'ru':ru,'en':en}
def dl(kind,label,date,url,zone='',time=False,note=None):
    x={'kind':kind,'label':label,'date':date,'timeKnown':time,'zone':zone,'url':url}
    if note is not None:x['note']=note
    return x

def ev(id,title,full,org,start,end,city,country,region,mode,venue,categories,official,description,*,level='regional',featured=False,submission=False,program=None,registration=None,submit=None,credits=None,deadlines=None,submission_note=None):
    x={'id':id,'featured':featured,'level':level,'title':title,'fullTitle':full,'org':org,'start':start,'end':end,'city':city,'country':country,'region':region,'mode':mode,'venue':venue,'categories':categories,'credits':credits or bi('CME/НМО: уточняется организатором','CME/CPD: check with organiser'),'submissionOpen':submission,'official':official,'program':program or official,'registration':registration or official,'submit':submit,'verified':VERIFIED,'description':description,'deadlines':deadlines or []}
    if submission_note:x['submissionNote']=submission_note
    return x

EVENTS=[
# China / Greater China
ev('ccos-2026',bi('CCOS 2026','CCOS 2026'),bi('30-й Китайский национальный конгресс по офтальмологии','30th Chinese Congress of Ophthalmology'),bi('Китайская медицинская ассоциация · Китайское офтальмологическое общество','Chinese Medical Association · Chinese Ophthalmological Society'),'2026-09-09','2026-09-12',bi('Тяньцзинь','Tianjin'),bi('Китай','China'),bi('Китай / Greater China','China / Greater China'),bi('Очно','In person'),bi('Национальный выставочный и конгресс-центр, Тяньцзинь','National Convention and Exhibition Center, Tianjin'),bi(['Катаракта / ИОЛ','Рефракция','Роговица','Retina','Глаукома','Research','AI / управление'],['Cataract / IOL','Refractive','Cornea','Retina','Glaucoma','Research','AI / management']),'https://ccos2026.sciconf.cn/',bi('Крупнейший национальный офтальмологический конгресс Китая: более 10 000 участников, все ключевые субспециальности, междисциплинарные исследования, генетика и искусственный интеллект.','China’s major national ophthalmology congress with more than 10,000 delegates expected, covering all major subspecialties, interdisciplinary research, genetics and AI.'),level='national',featured=True,registration='https://ccos2026.sciconf.cn/'),
ev('asmhk-2026',bi('Hong Kong Ophthalmological Symposium 2026','Hong Kong Ophthalmological Symposium 2026'),bi('38-я ежегодная научная встреча Hong Kong Ophthalmological Symposium','38th Annual Scientific Meeting Hong Kong Ophthalmological Symposium'),bi('College of Ophthalmologists of Hong Kong · Hong Kong Ophthalmological Society','College of Ophthalmologists of Hong Kong · Hong Kong Ophthalmological Society'),'2026-12-12','2026-12-13',bi('Гонконг','Hong Kong'),bi('Китай · Гонконг','Hong Kong, China'),bi('Китай / Greater China','China / Greater China'),bi('Очно','In person'),bi('Hong Kong Convention and Exhibition Centre','Hong Kong Convention and Exhibition Centre'),bi(['Retina','Research','AI / управление'],['Retina','Research','AI / management']),'https://asmhk2026.com/',bi('Флагманская встреча офтальмологов Гонконга. Тема 2026 года — Artificial Intelligence and Retinal Disease; предусмотрены оригинальные исследования, клинические обновления и хирургические дискуссии.','Hong Kong’s flagship ophthalmology meeting. The 2026 theme is Artificial Intelligence and Retinal Disease, with original research, clinical updates and surgical discussions.'),level='national',submission=True,program='https://asmhk2026.com/',registration='https://asmhk2026.com/',submit='https://asmhk2026.com/abstract-submission/',deadlines=[dl('abstract',bi('Закрытие подачи тезисов','Abstract submission closes'),'2026-09-11','https://asmhk2026.com/abstract-submission/','Asia/Hong_Kong',False)]),
ev('apspos-capos-2027',bi('APSPOS + CAPOS 2027','APSPOS + CAPOS 2027'),bi('4-й конгресс Asia-Pacific Strabismus and Paediatric Ophthalmology Society совместно с CAPOS','4th APSPOS Congress in conjunction with the 2027 CAPOS National Congress'),bi('APSPOS · CAPOS','APSPOS · CAPOS'),'2027-04-15','2027-04-17',bi('Тяньцзинь','Tianjin'),bi('Китай','China'),bi('Китай / Greater China','China / Greater China'),bi('Очно','In person'),bi('Shangri-La Tianjin','Shangri-La Tianjin'),bi(['Детская офтальмология','Страбизм','Роговица','Retina','Глаукома','Нейроофтальмология','Research','AI / управление'],['Pediatric ophthalmology','Strabismus','Cornea','Retina','Glaucoma','Neuro-ophthalmology','Research','AI / management']),'https://apspos.org/apspos-congress-2027/',bi('Крупная региональная встреча по детской офтальмологии и страбизмологии с секциями по миопии, наследственным заболеваниям, нейроофтальмологии, визуализации и ИИ.','Major regional paediatric ophthalmology and strabismus meeting, including myopia, hereditary eye disease, neuro-ophthalmology, imaging and AI.'),level='specialty',featured=True,submission=True,program='https://apspos-capos2027.sciconf.cn/',registration='https://apspos-capos2027.sciconf.cn/',submit='https://mm.sciconf.cn/en/web/index/35830_3124925',deadlines=[dl('abstract',bi('Тезисы: oral / poster / publication only','Abstracts: oral / poster / publication only'),'2026-12-01T23:59:00+08:00','https://mm.sciconf.cn/en/web/index/35830_3124925','UTC+8',True,bi('Дедлайн опубликован APSPOS.','Deadline published by APSPOS.'))]),
# Asia-Pacific
ev('pit-perdami-51-2026',bi('PIT PERDAMI 51','PIT PERDAMI 51'),bi('51-я ежегодная научная встреча PERDAMI — GAMBANG Semarang 2026','51st PERDAMI Annual Scientific Meeting — GAMBANG Semarang 2026'),bi('PERDAMI · Indonesian Ophthalmologists Association','PERDAMI · Indonesian Ophthalmologists Association'),'2026-09-03','2026-09-05',bi('Семаранг','Semarang'),bi('Индонезия','Indonesia'),bi('Азия–Тихоокеанский','Asia–Pacific'),bi('Очно','In person'),bi('Muladi Dome, Universitas Diponegoro','Muladi Dome, Universitas Diponegoro'),bi(['Катаракта / ИОЛ','Роговица','Retina','Глаукома','Детская офтальмология','Окулопластика','Research','AI / управление'],['Cataract / IOL','Cornea','Retina','Glaucoma','Pediatric ophthalmology','Oculoplastics','Research','AI / management']),'https://pit51.perdami.or.id/',bi('Национальная встреча офтальмологов Индонезии с симпозиумами, didactic courses, wet-labs, конкурсами научных работ и фокусом на AI и общественном здоровье глаз.','Indonesia’s national ophthalmology meeting with symposia, didactic courses, wet labs, research competitions and a focus on AI and community eye health.'),level='national',featured=True,registration='https://pit51.perdami.or.id/'),
ev('aios-midterm-2026',bi('AIOS Mid-term 2026','AIOS Mid-term 2026'),bi('5-я Mid-term Conference of All India Ophthalmological Society','5th Mid-term Conference of the All India Ophthalmological Society'),bi('All India Ophthalmological Society','All India Ophthalmological Society'),'2026-09-25','2026-09-27',bi('Ранчи','Ranchi'),bi('Индия','India'),bi('Азия–Тихоокеанский','Asia–Pacific'),bi('Очно','In person'),bi('Hotel Chanakya BNR, Ranchi','Hotel Chanakya BNR, Ranchi'),bi(['Катаракта / ИОЛ','Рефракция','Роговица','Retina','Глаукома','Research'],['Cataract / IOL','Refractive','Cornea','Retina','Glaucoma','Research']),'https://www.aios.org/midtermjharkhand.php',bi('Крупная межсъездовская конференция Всеиндийского офтальмологического общества с научной программой и отдельным порталом подачи тезисов.','Major mid-term meeting of the All India Ophthalmological Society with a scientific programme and a dedicated abstract submission portal.'),level='national',submission=True,registration='https://www.aios.org/midtermjharkhand.php',submit='https://www.aios.org/midtermjharkhand.php',submission_note=bi('На официальной странице доступен раздел Abstract Submission; точный текущий срок уточняйте в портале AIOS.','The official page provides an Abstract Submission portal; verify the current closing date in the AIOS portal.')),
ev('pao-annual-2026',bi('PAO Annual Convention 2026','PAO Annual Convention 2026'),bi('Ежегодный конгресс Philippine Academy of Ophthalmology','Philippine Academy of Ophthalmology Annual Convention'),bi('Philippine Academy of Ophthalmology','Philippine Academy of Ophthalmology'),'2026-09-29','2026-10-02',bi('Манила','Manila'),bi('Филиппины','Philippines'),bi('Азия–Тихоокеанский','Asia–Pacific'),bi('Очно','In person'),bi('SMX Convention Center, Manila','SMX Convention Center, Manila'),bi(['Катаракта / ИОЛ','Роговица','Retina','Глаукома','Детская офтальмология','Окулопластика'],['Cataract / IOL','Cornea','Retina','Glaucoma','Pediatric ophthalmology','Oculoplastics']),'https://pao.org.ph/eye-doctors-home-event/philippine-academy-of-ophthalmology-pao-annual-convention/',bi('Главная ежегодная встреча Philippine Academy of Ophthalmology с мультиспециализированной программой и национальными конкурсами.','The Philippine Academy of Ophthalmology’s main annual meeting, with a multispecialty programme and national scientific contests.'),level='national',registration='https://pao.org.ph/eye-doctors-home-event/philippine-academy-of-ophthalmology-pao-annual-convention/'),
ev('kos-apois-2026',bi('KOS / APOIS 2026','KOS / APOIS 2026'),bi('136-я встреча Korean Ophthalmological Society + 6-й APOIS + 19-я Korea-China-Japan Joint Meeting','136th Korean Ophthalmological Society Meeting + 6th APOIS + 19th Korea-China-Japan Joint Meeting'),bi('Korean Ophthalmological Society · APOIS','Korean Ophthalmological Society · APOIS'),'2026-10-30','2026-11-01',bi('Сеул','Seoul'),bi('Республика Корея','Republic of Korea'),bi('Азия–Тихоокеанский','Asia–Pacific'),bi('Очно','In person'),bi('Grand Walkerhill Seoul','Grand Walkerhill Seoul'),bi(['Катаракта / ИОЛ','Роговица','Retina','Глаукома','Детская офтальмология','Страбизм','Нейроофтальмология','Окулопластика','Research','AI / управление'],['Cataract / IOL','Cornea','Retina','Glaucoma','Pediatric ophthalmology','Strabismus','Neuro-ophthalmology','Oculoplastics','Research','AI / management']),'https://www.kosmeeting.org/abstract/2026_136/eng/main.html',bi('Большой осенний конгресс KOS, объединённый с APOIS и трёхсторонней встречей Корея–Китай–Япония; особый акцент на imaging, AI, новых терапиях и инновациях.','Major KOS autumn congress combined with APOIS and the Korea-China-Japan joint meeting, with emphasis on imaging, AI, new therapeutics and innovation.'),level='national',program='https://www.kosmeeting.org/abstract/2026_136/eng/main.html',registration='https://www.kosmeeting.org/abstract/2026_136/eng/main.html',deadlines=[dl('upload',bi('Финальная загрузка файлов презентаций','Presentation file upload closes'),'2026-09-30','https://www.kosmeeting.org/abstract/2026_136/eng/main.html','Asia/Seoul',False),dl('registration',bi('Закрытие предварительной регистрации','Pre-registration closes'),'2026-10-16','https://www.kosmeeting.org/abstract/2026_136/eng/main.html','Asia/Seoul',False)]),
ev('jco-80-2026',bi('80th Japan Clinical Ophthalmology Congress','80th Japan Clinical Ophthalmology Congress'),bi('80-й ежегодный конгресс Japan Clinical Ophthalmology','80th Annual Congress of Japan Clinical Ophthalmology'),bi('Japanese ophthalmology community · Mie University','Japanese ophthalmology community · Mie University'),'2026-10-29','2026-11-01',bi('Киото','Kyoto'),bi('Япония','Japan'),bi('Азия–Тихоокеанский','Asia–Pacific'),bi('Очно','In person'),bi('Kyoto International Conference Center + The Prince Kyoto Takaragaike','Kyoto International Conference Center + The Prince Kyoto Takaragaike'),bi(['Катаракта / ИОЛ','Роговица','Retina','Глаукома','Research'],['Cataract / IOL','Cornea','Retina','Glaucoma','Research']),'https://convention.jtbcom.co.jp/80ringan/en/index.html',bi('80-й юбилейный японский клинический офтальмологический конгресс с широкой научной и практической программой.','The 80th anniversary Japanese clinical ophthalmology congress with a broad scientific and clinical programme.'),level='national',registration='https://convention.jtbcom.co.jp/80ringan/en/registration/index.html',deadlines=[dl('registration',bi('Окончание early-bird регистрации','Early-bird registration closes'),'2026-09-25T12:00:00+09:00','https://convention.jtbcom.co.jp/80ringan/en/registration/index.html','JST / UTC+9',True)]),
ev('ranzco-2026',bi('RANZCO 2026','RANZCO 2026'),bi('57-й Annual Scientific Congress RANZCO','57th RANZCO Annual Scientific Congress'),bi('Royal Australian and New Zealand College of Ophthalmologists','Royal Australian and New Zealand College of Ophthalmologists'),'2026-11-06','2026-11-09',bi('Окленд','Auckland'),bi('Новая Зеландия','New Zealand'),bi('Азия–Тихоокеанский','Asia–Pacific'),bi('Очно','In person'),bi('New Zealand International Convention Centre','New Zealand International Convention Centre'),bi(['Катаракта / ИОЛ','Роговица','Retina','Глаукома','Воспаление','Research'],['Cataract / IOL','Cornea','Retina','Glaucoma','Inflammation','Research']),'https://ranzco.edu/congress/',bi('Главный ежегодный научный конгресс RANZCO с мультиспециализированной программой по клинической и хирургической офтальмологии.','RANZCO’s main annual scientific congress, covering clinical and surgical ophthalmology across subspecialties.'),level='regional',registration='https://ranzco.edu/congress/'),
# Middle East / MENA
ev('qatar-uveitis-2026',bi('Second Qatar Uveitis Conference','Second Qatar Uveitis Conference'),bi('Вторая Qatar Uveitis Conference','Second Qatar Uveitis Conference'),bi('Qatar Society of Ophthalmology · Middle East Africa Uveitis Society','Qatar Society of Ophthalmology · Middle East Africa Uveitis Society'),'2026-09-25','2026-09-26',bi('Доха','Doha'),bi('Катар','Qatar'),bi('Ближний Восток','Middle East'),bi('Очно','In person'),bi('Rotana City Centre, Doha','Rotana City Centre, Doha'),bi(['Воспаление','Retina','Research'],['Inflammation','Retina','Research']),'https://qataruveitiscare.com/',bi('Специализированная международная встреча по увеитам, глазной иммунологии и медицинской ретине с участием региональных и международных экспертов.','Specialist international meeting on uveitis, ocular immunology and medical retina with regional and international faculty.'),level='specialty',registration='https://qataruveitiscare.com/'),
ev('eso-2026',bi('ESO 2026','ESO 2026'),bi('23-я конференция Emirates Society of Ophthalmology','23rd Emirates Society of Ophthalmology Conference'),bi('Emirates Society of Ophthalmology','Emirates Society of Ophthalmology'),'2026-10-15','2026-10-17',bi('Абу-Даби','Abu Dhabi'),bi('ОАЭ','United Arab Emirates'),bi('Ближний Восток','Middle East'),bi('Очно','In person'),bi('Abu Dhabi, UAE','Abu Dhabi, UAE'),bi(['Катаракта / ИОЛ','Рефракция','Роговица','Retina','Глаукома','Воспаление','Детская офтальмология','Окулопластика','Research'],['Cataract / IOL','Refractive','Cornea','Retina','Glaucoma','Inflammation','Pediatric ophthalmology','Oculoplastics','Research']),'https://eso-conferences.com/',bi('Национальная платформа офтальмологов ОАЭ и одна из крупных встреч GCC: комплексная научная программа, хирургические техники, workshops и wet-labs.','The UAE’s national ophthalmology platform and a major GCC meeting, featuring a comprehensive scientific programme, surgical techniques, workshops and wet labs.'),level='national',featured=True,program='https://eso-conferences.com/eso2026/',registration='https://eso-conferences.com/'),
ev('sos-2026',bi('Saudi Ophthalmology 2026','Saudi Ophthalmology 2026'),bi('International Conference of the Saudi Ophthalmology Society 2026','International Conference of the Saudi Ophthalmology Society 2026'),bi('Saudi Ophthalmology Society','Saudi Ophthalmology Society'),'2026-11-04','2026-11-07',bi('Эль-Хубар','Al Khobar'),bi('Саудовская Аравия','Saudi Arabia'),bi('Ближний Восток','Middle East'),bi('Очно','In person'),bi('Grand Hyatt Al-Khobar','Grand Hyatt Al-Khobar'),bi(['Катаракта / ИОЛ','Рефракция','Роговица','Retina','Глаукома','Воспаление','Детская офтальмология','Окулопластика','Research','AI / управление'],['Cataract / IOL','Refractive','Cornea','Retina','Glaucoma','Inflammation','Pediatric ophthalmology','Oculoplastics','Research','AI / management']),'https://sos-conferences.com/',bi('Крупный национальный конгресс Саудовской Аравии: pre-conference по роговице и молодым офтальмологам 4 ноября, основной мультиспециализированный конгресс 5–7 ноября.','Saudi Arabia’s major national congress: cornea and young-ophthalmologist pre-conference on Nov 4, followed by a multispecialty main congress Nov 5–7.'),level='national',featured=True,submission=True,registration='https://sos-conferences.com/',submit='https://sos-conferences.com/abstract-2026/',submission_note=bi('Подача тезисов доступна на официальном сайте; дата закрытия на проверенной странице не указана.','Abstract submission is available on the official site; the checked page does not publish a closing date.')),
ev('joscrs-2026',bi('2nd JOSCRS International Meeting','2nd JOSCRS International Meeting'),bi('2-я международная встреча Jordanian Ophthalmological Society Cataract & Refractive Surgery','2nd Jordanian Ophthalmological Society Cataract & Refractive Surgery International Meeting'),bi('Jordanian Ophthalmological Society','Jordanian Ophthalmological Society'),'2026-11-18','2026-11-20',bi('Амман','Amman'),bi('Иордания','Jordan'),bi('Ближний Восток','Middle East'),bi('Очно','In person'),bi('The St. Regis Hotel, Amman','The St. Regis Hotel, Amman'),bi(['Катаракта / ИОЛ','Рефракция','Роговица','Глаукома','AI / управление'],['Cataract / IOL','Refractive','Cornea','Glaucoma','AI / management']),'https://www.jordan-valley.com/jos2026',bi('Международная встреча по катаракте, переднему сегменту, роговице, рефракционной хирургии и глаукоме с wet-labs и секцией AI.','International meeting on cataract, anterior segment, cornea, refractive surgery and glaucoma, with wet labs and an AI track.'),level='specialty',submission=True,program='https://www.jordan-valley.com/jos2026',registration='https://www.jordan-valley.com/jos2026',submit='https://www.jordan-valley.com/jos2026',deadlines=[dl('abstract',bi('Закрытие подачи тезисов','Abstract submission closes'),'2026-09-15','https://www.jordan-valley.com/jos2026','Asia/Amman',False)]),
ev('mioc-2026',bi('MIOC 2026','MIOC 2026'),bi('Muscat International Ophthalmology Conference 2026','Muscat International Ophthalmology Conference 2026'),bi('MIOC Organising Committee','MIOC Organising Committee'),'2026-12-03','2026-12-05',bi('Маскат','Muscat'),bi('Оман','Oman'),bi('Ближний Восток','Middle East'),bi('Очно','In person'),bi('JW Marriott, Muscat','JW Marriott, Muscat'),bi(['Катаракта / ИОЛ','Рефракция','Роговица','Retina','Глаукома','Research'],['Cataract / IOL','Refractive','Cornea','Retina','Glaucoma','Research']),'https://mioc.org.om/',bi('Международная офтальмологическая конференция в Маскате с free papers, clinical cases, posters, videos, wet-labs и образовательными курсами.','International ophthalmology meeting in Muscat with free papers, clinical cases, posters, videos, wet labs and educational courses.'),level='regional',featured=True,submission=True,program='https://mioc.org.om/',registration='https://mioc.org.om/important-dates',submit='https://mioc.org.om/abstract-submission',deadlines=[dl('abstract',bi('Закрытие подачи тезисов','Abstract submission deadline'),'2026-09-01','https://mioc.org.om/abstract-submission','Asia/Muscat',False),dl('registration',bi('Early-bird регистрация','Early-bird registration closes'),'2026-10-15','https://mioc.org.om/important-dates','Asia/Muscat',False),dl('registration',bi('Standard registration','Standard registration deadline'),'2026-11-20','https://mioc.org.om/important-dates','Asia/Muscat',False)]),
ev('epomec-2026',bi('EPOMEC 2026','EPOMEC 2026'),bi('13th Evolving Practice of Ophthalmology Middle East Conference','13th Evolving Practice of Ophthalmology Middle East Conference'),bi('EPOMEC','EPOMEC'),'2026-12-03','2026-12-05',bi('Дубай','Dubai'),bi('ОАЭ','United Arab Emirates'),bi('Ближний Восток','Middle East'),bi('Очно','In person'),bi('Dubai World Trade Centre','Dubai World Trade Centre'),bi(['Катаракта / ИОЛ','Рефракция','Роговица','Retina','Глаукома','Воспаление','Детская офтальмология','Окулопластика'],['Cataract / IOL','Refractive','Cornea','Retina','Glaucoma','Inflammation','Pediatric ophthalmology','Oculoplastics']),'https://www.epomec.ae/',bi('13-я MENA-конференция по современной офтальмологической практике в Дубае; организаторы ожидают более 3000 участников и экспонентов.','The 13th MENA meeting on evolving ophthalmic practice in Dubai; organisers expect more than 3,000 delegates and exhibitors.'),level='regional',registration='https://www.epomec.ae/'),
ev('escrs-winter-2027',bi('31st ESCRS Winter Meeting','31st ESCRS Winter Meeting'),bi('31-я зимняя встреча European Society of Cataract and Refractive Surgeons','31st Winter Meeting of the European Society of Cataract and Refractive Surgeons'),bi('ESCRS','ESCRS'),'2027-03-17','2027-03-20',bi('Каир','Cairo'),bi('Египет','Egypt'),bi('Ближний Восток','Middle East'),bi('Очно','In person'),bi('InterContinental CityStars, Cairo','InterContinental CityStars, Cairo'),bi(['Катаракта / ИОЛ','Рефракция','Роговица'],['Cataract / IOL','Refractive','Cornea']),'https://www.escrs.org/meetings-and-events',bi('Зимняя встреча ESCRS 2027 в Каире — специализированное международное событие по катарактальной, рефракционной и переднесегментной хирургии.','The 2027 ESCRS Winter Meeting in Cairo, focused on cataract, refractive and anterior-segment surgery.'),level='specialty',featured=True,registration='https://www.escrs.org/meetings-and-events'),
ev('amman-retina-2027',bi('Amman Retina Meeting 2027','Amman Retina Meeting 2027'),bi('Amman Retina Meeting 2027','Amman Retina Meeting 2027'),bi('Amman Retina Meeting','Amman Retina Meeting'),'2027-05-26','2027-05-28',bi('Амман','Amman'),bi('Иордания','Jordan'),bi('Ближний Восток','Middle East'),bi('Очно','In person'),bi('Fairmont Hotel Amman','Fairmont Hotel Amman'),bi(['Retina','Research'],['Retina','Research']),'https://www.ammanretinameeting.com/',bi('Специализированный международный конгресс по медицинской и хирургической ретине с международным faculty и практическими курсами.','Specialist international congress on medical and surgical retina with international faculty and practical courses.'),level='specialty',program='https://www.ammanretinameeting.com/',registration='https://www.ammanretinameeting.com/registration',submit='https://www.ammanretinameeting.com/abstract-submission',deadlines=[dl('registration',bi('Early-bird регистрация','Early-bird registration deadline'),'2027-01-30','https://www.ammanretinameeting.com/registration','Asia/Amman',False)],submission_note=bi('Раздел подачи тезисов опубликован как Coming Soon.','The abstract submission page is currently marked Coming Soon.')),
# Africa
ev('coecsa-2026',bi('COECSA 2026','COECSA 2026'),bi('13th COECSA Annual Scientific Congress','13th COECSA Annual Scientific Congress'),bi('College of Ophthalmology of Eastern, Central and Southern Africa · Ophthalmology Society of Uganda','College of Ophthalmology of Eastern, Central and Southern Africa · Ophthalmology Society of Uganda'),'2026-12-02','2026-12-04',bi('Кампала','Kampala'),bi('Уганда','Uganda'),bi('Африка','Africa'),bi('Очно','In person'),bi('Serena Hotel, Kampala','Serena Hotel, Kampala'),bi(['Катаракта / ИОЛ','Роговица','Retina','Глаукома','Research'],['Cataract / IOL','Cornea','Retina','Glaucoma','Research']),'https://www.coecsa-congress.org/',bi('13-й научный конгресс COECSA по офтальмологии Восточной, Центральной и Южной Африки. Официально перенесён на 2–4 декабря 2026 года.','The 13th COECSA scientific congress for Eastern, Central and Southern Africa. Officially rescheduled to Dec 2–4, 2026.'),level='regional',featured=True,registration='https://www.coecsa-congress.org/'),
ev('ossa-2027',bi('OSSA Congress 2027','OSSA Congress 2027'),bi('Конгресс Ophthalmological Society of South Africa 2027','Ophthalmological Society of South Africa Congress 2027'),bi('Ophthalmological Society of South Africa','Ophthalmological Society of South Africa'),'2027-03-10','2027-03-13',bi('Кейптаун','Cape Town'),bi('ЮАР','South Africa'),bi('Африка','Africa'),bi('Очно','In person'),bi('Cape Town, South Africa','Cape Town, South Africa'),bi(['Катаракта / ИОЛ','Рефракция','Роговица','Retina','Глаукома','Окулопластика','Research'],['Cataract / IOL','Refractive','Cornea','Retina','Glaucoma','Oculoplastics','Research']),'https://ossacongress.co.za/',bi('Национальный офтальмологический конгресс ЮАР: masterclasses 10 марта и основная научная программа 11–13 марта.','South Africa’s national ophthalmology congress, with masterclasses on Mar 10 and the main scientific programme Mar 11–13.'),level='national',featured=True,submission=True,program='https://ossacongress.co.za/programme/',registration='https://ossacongress.co.za/',submit='https://ossacongress.co.za/programme/',deadlines=[dl('abstract',bi('Закрытие подачи тезисов','Abstract submission deadline'),'2026-08-28','https://ossacongress.co.za/introduction/','Africa/Johannesburg',False)]),
# Latin America
ev('latam-glaucoma-2026',bi('XIII Latin American Glaucoma Congress','XIII Latin American Glaucoma Congress'),bi('XIII Congreso Latinoamericano de Glaucoma','XIII Congreso Latinoamericano de Glaucoma'),bi('Sociedad Latinoamericana de Glaucoma','Latin American Glaucoma Society'),'2026-09-24','2026-09-26',bi('Кито','Quito'),bi('Эквадор','Ecuador'),bi('Латинская Америка','Latin America'),bi('Очно','In person'),bi('JW Marriott, Quito','JW Marriott, Quito'),bi(['Глаукома'],['Glaucoma']),'https://paao.org/events/xiii-congreso-latinoamericano-de-glaucoma/',bi('Крупная специализированная латиноамериканская встреча по глаукоме.','Major Latin American specialist meeting focused on glaucoma.'),level='specialty',registration='https://www.slaglaucoma.org/'),
ev('alaccsa-r-2026',bi('ALACCSA-R 2026','ALACCSA-R 2026'),bi('XXVI ALACCSA-R International Congress 2026','XXVI ALACCSA-R International Congress 2026'),bi('ALACCSA-R','ALACCSA-R'),'2026-10-22','2026-10-24',bi('Асунсьон','Asunción'),bi('Парагвай','Paraguay'),bi('Латинская Америка','Latin America'),bi('Очно','In person'),bi('Asunción, Paraguay','Asunción, Paraguay'),bi(['Катаракта / ИОЛ','Рефракция','Роговица'],['Cataract / IOL','Refractive','Cornea']),'https://paao.org/events/alaccsa-2026/',bi('26-й международный конгресс ALACCSA-R по катаракте, рефракционной хирургии и переднему сегменту.','26th ALACCSA-R International Congress focused on cataract, refractive surgery and anterior segment.'),level='specialty',registration='https://alaccsa.com/'),
ev('sprv-2026',bi('Pan-American Retina & Vitreous Congress 2026','Pan-American Retina & Vitreous Congress 2026'),bi('11-й конгресс Pan-American Retina & Vitreous Society + 20-й GLADAOF Forum','11th Pan-American Retina & Vitreous Society Congress + 20th GLADAOF Forum'),bi('Sociedad Panamericana de Retina y Vítreo · GLADAOF','Pan-American Retina & Vitreous Society · GLADAOF'),'2026-10-29','2026-11-01',bi('Сан-Паулу','São Paulo'),bi('Бразилия','Brazil'),bi('Латинская Америка','Latin America'),bi('Очно','In person'),bi('Grand Hyatt, São Paulo','Grand Hyatt, São Paulo'),bi(['Retina','Research'],['Retina','Research']),'https://paao.org/events/sprv-2026/',bi('Панамериканская специализированная встреча по заболеваниям сетчатки и витреоретинальной хирургии.','Pan-American specialist meeting on retinal disease and vitreoretinal surgery.'),level='specialty',featured=True,registration='https://sprv2026.com/'),
ev('sopla-2027',bi('III SOPLA International Congress','III SOPLA International Congress'),bi('III Международный конгресс SOPLA по детской офтальмологии','III SOPLA International Congress of Pediatric Ophthalmology'),bi('SOPLA · Sociedad de Oftalmo Pediatría LatinoAmericana','SOPLA · Sociedad de Oftalmo Pediatría LatinoAmericana'),'2027-02-05','2027-02-07',bi('Медельин','Medellín'),bi('Колумбия','Colombia'),bi('Латинская Америка','Latin America'),bi('Очно','In person'),bi('Hotel Intercontinental Movich Medellin','Hotel Intercontinental Movich Medellin'),bi(['Детская офтальмология','Страбизм'],['Pediatric ophthalmology','Strabismus']),'https://paao.org/events/iii-sopla-international-congress-of-pediatric-ophthalmology/',bi('Международный латиноамериканский конгресс по детской офтальмологии и страбизмологии.','International Latin American congress focused on paediatric ophthalmology and strabismus.'),level='specialty',registration='https://www.sopla.org/Congreso/Congreso2026'),
ev('paao-2027',bi('PAAO 2027','PAAO 2027'),bi('37-й Pan-American Congress of Ophthalmology','37th Pan-American Congress of Ophthalmology'),bi('Pan-American Association of Ophthalmology · Sociedad Peruana de Oftalmología','Pan-American Association of Ophthalmology · Peruvian Society of Ophthalmology'),'2027-03-17','2027-03-20',bi('Лима','Lima'),bi('Перу','Peru'),bi('Латинская Америка','Latin America'),bi('Очно','In person'),bi('Lima Convention Center','Lima Convention Center'),bi(['Катаракта / ИОЛ','Рефракция','Роговица','Retina','Глаукома','Воспаление','Детская офтальмология','Страбизм','Нейроофтальмология','Окулопластика','Research'],['Cataract / IOL','Refractive','Cornea','Retina','Glaucoma','Inflammation','Pediatric ophthalmology','Strabismus','Neuro-ophthalmology','Oculoplastics','Research']),'https://paao2027.com/landing/',bi('Главный Панамериканский конгресс 2027 года в Лиме, ожидающий более 5000 участников и охватывающий все ключевые субспециальности.','The flagship Pan-American ophthalmology congress in Lima, expected to bring together more than 5,000 delegates across all major subspecialties.'),level='major',featured=True,submission=True,program='https://paao2027.com/landing/program/',registration='https://paao2027.com/landing/',submit='https://abstracts.paao2027.com/',deadlines=[dl('registration',bi('Early-bird регистрация','Early-bird registration deadline'),'2026-10-15','https://paao2027.com/landing/','America/Lima',False)],submission_note=bi('Портал подачи free papers, videos и posters открыт; точный дедлайн на проверенной публичной странице не указан.','The free paper, video and poster submission portal is open; no exact closing date is published on the checked public page.')),
# Europe
ev('dog-2026',bi('DOG 2026','DOG 2026'),bi('Конгресс Deutsche Ophthalmologische Gesellschaft 2026','German Ophthalmological Society Congress 2026'),bi('DOG · Deutsche Ophthalmologische Gesellschaft','DOG · German Ophthalmological Society'),'2026-09-24','2026-09-27',bi('Берлин','Berlin'),bi('Германия','Germany'),bi('Европа','Europe'),bi('Очно + online sessions','In person + online sessions'),bi('Estrel Congress Center, Berlin','Estrel Congress Center, Berlin'),bi(['Катаракта / ИОЛ','Роговица','Retina','Глаукома','Research','AI / управление'],['Cataract / IOL','Cornea','Retina','Glaucoma','Research','AI / management']),'https://dog-kongress.de/',bi('Главный ежегодный конгресс German Ophthalmological Society под темой «Офтальмология без границ», с клиническими, хирургическими и исследовательскими секциями.','The German Ophthalmological Society’s main annual congress, themed “Ophthalmology without borders,” with clinical, surgical and research tracks.'),level='national',featured=True,program='https://dog-kongress.de/',registration='https://dog-kongress.de/'),
ev('spanish-national-2026',bi('Spanish National Meeting 2026','Spanish National Meeting 2026'),bi('102-й национальный конгресс Sociedad Española de Oftalmología','102nd National Congress of the Spanish Society of Ophthalmology'),bi('Sociedad Española de Oftalmología','Spanish Society of Ophthalmology'),'2026-09-23','2026-09-26',bi('Пальма-де-Майорка','Palma de Mallorca'),bi('Испания','Spain'),bi('Европа','Europe'),bi('Очно','In person'),bi('Palma de Mallorca, Spain','Palma de Mallorca, Spain'),bi(['Катаракта / ИОЛ','Роговица','Retina','Глаукома','Research'],['Cataract / IOL','Cornea','Retina','Glaucoma','Research']),'https://soevision.org/event/spanish-national-meeting/',bi('Национальная встреча Испанского офтальмологического общества 2026 года.','The 2026 national meeting of the Spanish Society of Ophthalmology.'),level='national',registration='https://www.oftalmo.com/seo'),
ev('czech-national-2026',bi('Czech Ophthalmology 2026','Czech Ophthalmology 2026'),bi('Национальная встреча Czech Ophthalmology Society 2026','Czech Ophthalmology National Society Meeting 2026'),bi('Czech ophthalmology community','Czech ophthalmology community'),'2026-10-01','2026-10-03',bi('Острава','Ostrava'),bi('Чехия','Czech Republic'),bi('Европа','Europe'),bi('Очно','In person'),bi('Ostrava, Czech Republic','Ostrava, Czech Republic'),bi(['Катаракта / ИОЛ','Роговица','Retina','Глаукома'],['Cataract / IOL','Cornea','Retina','Glaucoma']),'https://soevision.org/ophthagenda/category/national-society-meetings/list/',bi('Национальная офтальмологическая встреча Чехии 1–3 октября 2026 года в Остраве.','Czech national ophthalmology meeting in Ostrava, Oct 1–3, 2026.'),level='national'),
ev('ever-2026',bi('EVER 2026','EVER 2026'),bi('European Association for Vision and Eye Research Congress 2026','European Association for Vision and Eye Research Congress 2026'),bi('EVER · European Association for Vision and Eye Research','EVER · European Association for Vision and Eye Research'),'2026-10-15','2026-10-17',bi('Флоренция','Florence'),bi('Италия','Italy'),bi('Европа','Europe'),bi('Очно','In person'),bi('Palazzo degli Affari, Florence','Palazzo degli Affari, Florence'),bi(['Research','Retina','Роговица','Глаукома'],['Research','Retina','Cornea','Glaucoma']),'https://soevision.org/event/ever-2026/',bi('Европейский исследовательский конгресс по зрению и офтальмологии с фокусом на фундаментальную, трансляционную и клиническую науку.','European eye and vision research congress focused on basic, translational and clinical science.'),level='research',registration='https://evercongress.org/'),
ev('trends-retina-2026',bi('Trends in Retina 2026','Trends in Retina 2026'),bi('Trends in Retina Congress 2026','Trends in Retina Congress 2026'),bi('Trends in Retina','Trends in Retina'),'2026-11-12','2026-11-14',bi('Барселона','Barcelona'),bi('Испания','Spain'),bi('Европа','Europe'),bi('Очно','In person'),bi('Barcelona, Spain','Barcelona, Spain'),bi(['Retina','Research'],['Retina','Research']),'https://soevision.org/ophthagenda/list/',bi('Европейская специализированная встреча по современной диагностике и лечению заболеваний сетчатки.','European specialist meeting on contemporary retinal diagnosis and treatment.'),level='specialty'),
ev('soe-2027',bi('SOE 2027','SOE 2027'),bi('25-й конгресс European Society of Ophthalmology','25th Congress of the European Society of Ophthalmology'),bi('European Society of Ophthalmology · ISOT · EUPO','European Society of Ophthalmology · ISOT · EUPO'),'2027-06-18','2027-06-20',bi('Афины','Athens'),bi('Греция','Greece'),bi('Европа','Europe'),bi('Очно','In person'),bi('Megaron Congress Centre, Athens','Megaron Congress Centre, Athens'),bi(['Катаракта / ИОЛ','Роговица','Retina','Глаукома','Детская офтальмология','Окулопластика','Research'],['Cataract / IOL','Cornea','Retina','Glaucoma','Pediatric ophthalmology','Oculoplastics','Research']),'https://soe2027.soevision.org/',bi('25-й юбилейный мультиспециализированный конгресс SOE в Афинах совместно с ISOT и EUPO; симпозиумы, workshops, live surgery, debates и ocular trauma.','The 25th SOE multispecialty congress in Athens, held with ISOT and EUPO, featuring symposia, workshops, live surgery, debates and ocular trauma.'),level='major',featured=True,registration='https://soe2027.soevision.org/'),
# North America
ev('aao-2026',bi('AAO 2026','AAO 2026'),bi('Ежегодная встреча American Academy of Ophthalmology 2026','American Academy of Ophthalmology Annual Meeting 2026'),bi('American Academy of Ophthalmology','American Academy of Ophthalmology'),'2026-10-09','2026-10-12',bi('Новый Орлеан','New Orleans'),bi('США','USA'),bi('Северная Америка','North America'),bi('Очно','In person'),bi('New Orleans, Louisiana','New Orleans, Louisiana'),bi(['Катаракта / ИОЛ','Рефракция','Роговица','Retina','Глаукома','Воспаление','Детская офтальмология','Страбизм','Нейроофтальмология','Окулопластика'],['Cataract / IOL','Refractive','Cornea','Retina','Glaucoma','Inflammation','Pediatric ophthalmology','Strabismus','Neuro-ophthalmology','Oculoplastics']),'https://www.aao.org/annual-meeting',bi('Ежегодная встреча American Academy of Ophthalmology — одна из крупнейших мультиспециализированных офтальмологических встреч мира.','The American Academy of Ophthalmology Annual Meeting, one of the world’s largest multispecialty ophthalmology meetings.'),level='major',featured=True,registration='https://www.aao.org/annual-meeting'),
ev('aapos-2027',bi('AAPOS 2027','AAPOS 2027'),bi('52-я Annual Meeting American Association for Pediatric Ophthalmology and Strabismus','52nd Annual Meeting of the American Association for Pediatric Ophthalmology and Strabismus'),bi('AAPOS','AAPOS'),'2027-03-17','2027-03-21',bi('Вашингтон, округ Колумбия','Washington, DC'),bi('США','USA'),bi('Северная Америка','North America'),bi('Очно','In person'),bi('Washington, DC','Washington, DC'),bi(['Детская офтальмология','Страбизм','Research'],['Pediatric ophthalmology','Strabismus','Research']),'https://www.aapos.org/education-and-events/annual-meeting2026368',bi('52-я ежегодная специализированная встреча AAPOS по детской офтальмологии и страбизмологии.','The 52nd AAPOS specialist annual meeting in paediatric ophthalmology and strabismus.'),level='specialty',submission=False,program='https://www.aapos.org/education-and-events/annual-meeting2026368',registration='https://www.aapos.org/education-and-events/annual-meeting2026368',submit='https://www.aapos.org/education-and-events/annual-meeting2026368',deadlines=[dl('abstract',bi('Закрытие подачи тезисов','Abstract submission deadline'),'2026-09-22','https://www.aapos.org/education-and-events/annual-meeting2026368','America/New_York',False,bi('Подача открывается 17 августа 2026 года.','Submission opens Aug 17, 2026.')),dl('faculty',bi('Регистрация докладчиков','Presenter registration deadline'),'2026-12-15','https://www.aapos.org/education-and-events/annual-meeting2026368','America/New_York',False),dl('registration',bi('Early registration','Early registration deadline'),'2027-01-14','https://www.aapos.org/education-and-events/annual-meeting2026368','America/New_York',False)]),
ev('asrs-2027',bi('ASRS Annual Meeting 2027','ASRS Annual Meeting 2027'),bi('Annual Meeting American Society of Retina Specialists 2027','American Society of Retina Specialists Annual Meeting 2027'),bi('American Society of Retina Specialists','American Society of Retina Specialists'),'2027-07-28','2027-07-31',bi('Сан-Франциско','San Francisco'),bi('США','USA'),bi('Северная Америка','North America'),bi('Очно','In person'),bi('San Francisco, California','San Francisco, California'),bi(['Retina'],['Retina']),'https://www.asrs.org/annual-meeting/future-annual-meetings',bi('Будущая ежегодная встреча American Society of Retina Specialists — одна из ключевых международных конференций для витреоретинальных специалистов.','Future annual meeting of the American Society of Retina Specialists, a major international meeting for vitreoretinal specialists.'),level='specialty'),
]

def pick(v,lang):
    if isinstance(v,dict):
        if set(v.keys()).issubset({'ru','en'}) and lang in v:return pick(v[lang],lang)
        return {k:pick(val,lang) for k,val in v.items()}
    if isinstance(v,list):return [pick(x,lang) for x in v]
    return v

def upsert_events(path,lang):
    payload=json.loads(path.read_text(encoding='utf-8'))
    old={e['id']:e for e in payload['events']}
    for raw in EVENTS: old[raw['id']]=pick(raw,lang)
    if 'acs-2026' in old: old['acs-2026']['region']='Китай / Greater China' if lang=='ru' else 'China / Greater China'
    payload['events']=sorted(old.values(),key=lambda e:(e['start'],e['id']))
    payload['verifiedAt']=VERIFIED
    payload['generatedAt']=datetime.now(timezone.utc).isoformat(timespec='seconds')
    path.write_text(json.dumps(payload,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
    return set(old)

ru_ids=upsert_events(DATA/'ophthalmology-events.ru.json','ru')
en_ids=upsert_events(DATA/'ophthalmology-events.en.json','en')
assert ru_ids==en_ids

SOURCES=[
('ccos-global','https://ccos2026.sciconf.cn/',['ccos-2026'],['2026年09月09-12日','中华医学会第三十次眼科学术大会']),
('asmhk-global','https://asmhk2026.com/',['asmhk-2026'],['December 12','Artificial Intelligence and Retinal Disease']),
('apspos-global','https://apspos.org/apspos-congress-2027/',['apspos-capos-2027'],['December 1, 2026','APSPOS Congress 2027']),
('pit-perdami-global','https://pit51.perdami.or.id/',['pit-perdami-51-2026'],['September 3','Semarang']),
('aios-midterm-global','https://www.aios.org/midtermjharkhand.php',['aios-midterm-2026'],['September 25','Ranchi']),
('pao-annual-global','https://pao.org.ph/eye-doctors-home-event/philippine-academy-of-ophthalmology-pao-annual-convention/',['pao-annual-2026'],['September 29','SMX Convention Center']),
('kos-apois-global','https://www.kosmeeting.org/abstract/2026_136/eng/main.html',['kos-apois-2026'],['Pre-registration','Presentation File Upload']),
('jco80-global','https://convention.jtbcom.co.jp/80ringan/en/index.html',['jco-80-2026'],['October 29','November 1']),
('ranzco-global','https://ranzco.edu/congress/',['ranzco-2026'],['6-9 November 2026','Auckland']),
('qatar-uveitis-global','https://qataruveitiscare.com/',['qatar-uveitis-2026'],['25th','September, 2026']),
('eso-global','https://eso-conferences.com/',['eso-2026'],['15–17 October, 2026','Abu Dhabi']),
('sos-global','https://sos-conferences.com/',['sos-2026'],['5–7 November 2026','Al Khobar']),
('joscrs-global','https://www.jordan-valley.com/jos2026',['joscrs-2026'],['18–20 November 2026','15 September 2026']),
('mioc-global','https://mioc.org.om/important-dates',['mioc-2026'],['1 September','20 November']),
('epomec-global','https://www.epomec.ae/welcome-message/',['epomec-2026'],['3-5 December 2026','Dubai World Trade Centre']),
('escrs-winter-global','https://www.escrs.org/meetings-and-events',['escrs-winter-2027'],['31st ESCRS Winter Meeting','17 March']),
('amman-retina-global','https://www.ammanretinameeting.com/',['amman-retina-2027'],['26-28 May 2027','Amman']),
('coecsa-global','https://www.coecsa-congress.org/',['coecsa-2026'],['2-4th December 2026','Kampala']),
('ossa-global','https://ossacongress.co.za/introduction/',['ossa-2027'],['28 August 2026','10 -13 March 2027']),
('latam-glaucoma-global','https://paao.org/events/xiii-congreso-latinoamericano-de-glaucoma/',['latam-glaucoma-2026'],['24 September 2026','Quito']),
('alaccsa-global','https://paao.org/events/alaccsa-2026/',['alaccsa-r-2026'],['22 October 2026','Asunción']),
('sprv-global','https://paao.org/events/sprv-2026/',['sprv-2026'],['29 October 2026','Sao Paulo']),
('sopla-global','https://paao.org/events/iii-sopla-international-congress-of-pediatric-ophthalmology/',['sopla-2027'],['5 February 2027','Medellín']),
('paao-global','https://paao2027.com/landing/',['paao-2027'],['March 17th to 20th','Lima Convention Center']),
('dog-global','https://dog-kongress.de/',['dog-2026'],['24','27. September']),
('spanish-global','https://soevision.org/event/spanish-national-meeting/',['spanish-national-2026'],['September 23','Palma de Mallorca']),
('czech-global','https://soevision.org/ophthagenda/category/national-society-meetings/list/',['czech-national-2026'],['October 1','Ostrava']),
('ever-global','https://soevision.org/event/ever-2026/',['ever-2026'],['October 15','Florence']),
('trends-retina-global','https://soevision.org/ophthagenda/list/',['trends-retina-2026'],['Trends in Retina','November 12']),
('soe2027-global','https://soe2027.soevision.org/',['soe-2027'],['18th - 20th June 2027','Athens']),
('aao2026-global','https://apaophth.org/congress/calendar/',['aao-2026'],['AAO 2026','New Orleans']),
('aapos-global','https://www.aapos.org/education-and-events/annual-meeting2026368',['aapos-2027'],['Sep 22','Mar 17-21']),
('asrs-global','https://www.asrs.org/annual-meeting/future-annual-meetings',['asrs-2027'],['2027','San Francisco']),
]
sp=DATA/'ophthalmology-event-sources.json'
src=json.loads(sp.read_text(encoding='utf-8'))
by={s['id']:s for s in src['sources']}
for sid,url,eids,terms in SOURCES:by[sid]={'id':sid,'official':True,'url':url,'eventIds':eids,'watchTerms':terms}
src['sources']=sorted(by.values(),key=lambda s:s['id'])
sp.write_text(json.dumps(src,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')

REGIONS_RU=[('all','Все'),('Россия','Россия'),('СНГ','СНГ'),('Европа','Европа'),('Китай / Greater China','Китай / Greater China'),('Азия–Тихоокеанский','Азия–Тихоокеанский'),('Ближний Восток','Ближний Восток'),('Африка','Африка'),('Северная Америка','Северная Америка'),('Латинская Америка','Латинская Америка')]
REGIONS_EN=[('all','All'),('Russia','Russia'),('CIS','CIS'),('Europe','Europe'),('China / Greater China','China / Greater China'),('Asia–Pacific','Asia–Pacific'),('Middle East','Middle East'),('Africa','Africa'),('North America','North America'),('Latin America','Latin America')]
SPECS_RU=[('all','Все'),('Катаракта / ИОЛ','Катаракта / ИОЛ'),('Рефракция','Рефракция'),('Роговица','Роговица'),('Retina','Retina'),('Глаукома','Глаукома'),('Воспаление','Воспаление'),('Детская офтальмология','Детская офтальмология'),('Страбизм','Страбизм'),('Нейроофтальмология','Нейроофтальмология'),('Окулопластика','Окулопластика'),('Research','Research'),('AI / управление','AI / управление')]
SPECS_EN=[('all','All'),('Cataract / IOL','Cataract / IOL'),('Refractive','Refractive'),('Cornea','Cornea'),('Retina','Retina'),('Glaucoma','Glaucoma'),('Inflammation','Inflammation'),('Pediatric ophthalmology','Pediatric ophthalmology'),('Strabismus','Strabismus'),('Neuro-ophthalmology','Neuro-ophthalmology'),('Oculoplastics','Oculoplastics'),('Research','Research'),('AI / management','AI / management')]

def buttons(items,attr):
    return ''.join(f'<button class="filter-chip{" active" if key=="all" else ""}" type="button" data-{attr}="{key}">{label}</button>' for key,label in items)

def patch_page(path,lang):
    s=path.read_text(encoding='utf-8')
    regs=REGIONS_RU if lang=='ru' else REGIONS_EN
    specs=SPECS_RU if lang=='ru' else SPECS_EN
    s=re.sub(r'(<div class="filter-scroll" id="region-filters"[^>]*>).*?(</div></div><div class="filter-block">)',lambda m:m.group(1)+buttons(regs,'region')+m.group(2),s,count=1)
    s=re.sub(r'(<div class="filter-scroll" id="specialty-filters"[^>]*>).*?(</div></div><div class="toggles">)',lambda m:m.group(1)+buttons(specs,'specialty')+m.group(2),s,count=1)
    s=re.sub(r'<p class="hero-note">.*?</p>','',s,count=1)
    if lang=='ru':
        s=s.replace('Профессиональный календарь · Россия · СНГ · Азия–Тихоокеанский регион · мир','Профессиональный календарь · Россия · СНГ · Европа · Азия · Ближний Восток · Африка · Америка')
        s=s.replace('<span class="meta-chip">РФ, СНГ и Азия–Тихоокеанский регион</span>','<span class="meta-chip">Россия, СНГ и весь мир</span>')
        s=re.sub(r'<meta name="description" content="[^"]*">','<meta name="description" content="Мировой календарь офтальмологических конгрессов: Россия, СНГ, Китай, Азия, Ближний Восток, Европа, Африка и Америка — события, дедлайны и регистрация.">',s,count=1)
    else:
        s=s.replace('Professional calendar · Russia · CIS · Asia–Pacific · worldwide','Professional calendar · Russia · CIS · Europe · Asia · Middle East · Africa · Americas')
        s=s.replace('<span class="meta-chip">Russia, CIS and Asia–Pacific</span>','<span class="meta-chip">Russia, CIS and worldwide</span>')
        s=re.sub(r'<meta name="description" content="[^"]*">','<meta name="description" content="Global ophthalmology congress calendar covering Russia, CIS, China, Asia-Pacific, Middle East, Europe, Africa and the Americas — events, deadlines and registration.">',s,count=1)
    path.write_text(s,encoding='utf-8')

patch_page(ROOT/'for-doctors/events/index.html','ru')
patch_page(ROOT/'en/for-doctors/events/index.html','en')
print(f'Global events expansion applied: {len(EVENTS)} upserts; total={len(ru_ids)}')
