(function(){
const lang=(document.documentElement.lang||'ru').toLowerCase().startsWith('en')?'en':'ru';
const T=lang==='en'?{
 all:'All questions',short:'Short answer',details:'Details',important:'Important',review:'Medical review: 20 July 2026',copy:'Copy link',copied:'Link copied',topic:'Open topic page →',results:n=>`${n} ${n===1?'answer':'answers'} shown`,search:n=>`${n} ${n===1?'answer':'answers'} found`,empty:'No answers found. Try another word or clear the search.',query:'for'
}:{
 all:'Все вопросы',short:'Короткий ответ',details:'Подробнее',important:'Что важно',review:'Медицинская проверка: 20.07.2026',copy:'Скопировать ссылку',copied:'Ссылка скопирована',topic:'Открыть тематическую страницу →',results:n=>`Показано: ${n} ${pluralRu(n,'ответ','ответа','ответов')}`,search:n=>`Найдено: ${n} ${pluralRu(n,'ответ','ответа','ответов')}`,empty:'По вашему запросу ничего не найдено. Попробуйте другое слово или очистите поиск.',query:'по запросу'
};
function pluralRu(n,one,few,many){const a=Math.abs(n)%100,b=a%10;return a>10&&a<20?many:b>1&&b<5?few:b===1?one:many}
const DATA=window.PATIENT_FAQ_DATA||{categories:[],faqs:[]},VIDEOS=window.PATIENT_VIDEOS||{};
const TOPIC_URLS=lang==='en'?{before:'/en/patients/before-surgery/',day:'/en/patients/surgery-day/',early:'/en/patients/recovery/',daily:'/en/patients/daily-life/',drops:'/en/patients/eye-drops/',glasses:'/en/patients/glasses/'}:{before:'/patients/before-surgery/',day:'/patients/surgery-day/',early:'/patients/recovery/',daily:'/patients/daily-life/',drops:'/patients/eye-drops/',glasses:'/patients/glasses/'};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/ё/g,'е').replace(/[ьъ]/g,'').replace(/[^a-zа-я0-9]+/gi,' ').trim();
const words=v=>norm(v).split(/\s+/).filter(Boolean);
const questionCount=n=>lang==='en'?`${n} ${n===1?'question':'questions'}`:`${n} ${pluralRu(n,'вопрос','вопроса','вопросов')}`;
const path=document.getElementById('path-grid'),filters=document.getElementById('filter-row'),groups=document.getElementById('faq-groups'),search=document.getElementById('faq-search'),empty=document.getElementById('search-empty'),status=document.getElementById('search-status'),clear=document.getElementById('search-clear');
function video(id){const v=VIDEOS[id];if(!v)return '';if(v.kind==='youtube')return `<aside class="video-slot"><iframe src="${esc(v.src)}" title="${esc(v.title||'Video answer')}" loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></aside>`;return `<aside class="video-slot"><video controls playsinline preload="metadata" src="${esc(v.src)}"${v.poster?` poster="${esc(v.poster)}"`:''}></video></aside>`}
function item(f){const ps=f.paragraphs.map(p=>`<p>${esc(p)}</p>`).join(''),li=f.important.map(x=>`<li>${esc(x)}</li>`).join(''),index=[f.q,f.short,...f.paragraphs,...f.important].join(' '),hasVideo=Boolean(VIDEOS[f.id]);return `<details class="faq-item" id="${esc(f.id)}" data-category="${esc(f.cat)}" data-search="${esc(index)}"><summary><span class="faq-question">${esc(f.q)}</span><span class="faq-toggle" aria-hidden="true">+</span></summary><div class="faq-content ${hasVideo?'has-video':'no-video'}"><div class="answer-copy"><p class="short-answer"><span>${T.short}</span>${esc(f.short)}</p><div class="answer-detail"><h4>${T.details}</h4>${ps}</div><div class="answer-important"><h4>${T.important}</h4><ul>${li}</ul></div><div class="answer-meta"><span>${T.review}</span><button class="copy-link" type="button" data-copy-id="${esc(f.id)}">${T.copy}</button></div></div>${video(f.id)}</div></details>`}
path.innerHTML=DATA.categories.map(c=>`<a class="path-card" href="${TOPIC_URLS[c.key]||'#section-'+c.key}"><span>${c.number}</span><h3>${esc(c.title)}</h3><p>${esc(c.description)}</p><strong>${questionCount(DATA.faqs.filter(f=>f.cat===c.key).length)} →</strong></a>`).join('');
filters.innerHTML=`<button class="filter-button active" type="button" data-filter="all">${T.all}</button>`+DATA.categories.map(c=>`<button class="filter-button" type="button" data-filter="${c.key}">${esc(c.title)}</button>`).join('');
groups.innerHTML=DATA.categories.map(c=>`<section class="faq-group" id="section-${c.key}" data-category-section="${c.key}"><div class="faq-group-head"><span>${c.number}</span><div><p>${esc(c.description)}</p><h2>${esc(c.title)}</h2><a class="topic-page-link" href="${TOPIC_URLS[c.key]}">${T.topic}</a></div></div><div class="faq-list">${DATA.faqs.filter(f=>f.cat===c.key).map(item).join('')}</div></section>`).join('');
let active='all';
function setActive(value){active=value;filters.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x.dataset.filter===value))}
function apply(){const raw=(search.value||'').trim(),tokens=words(raw),isSearching=tokens.length>0;let n=0;document.querySelectorAll('.faq-item').forEach(el=>{const hay=norm(el.dataset.search),matchesText=!isSearching||tokens.every(t=>hay.includes(t)),matchesCategory=active==='all'||el.dataset.category===active,show=matchesText&&matchesCategory;el.hidden=!show;if(isSearching)el.open=show;else if(!show)el.open=false;if(show)n++});document.querySelectorAll('.faq-group').forEach(g=>g.hidden=![...g.querySelectorAll('.faq-item')].some(x=>!x.hidden));empty.hidden=n!==0;empty.textContent=T.empty;if(status){status.textContent=isSearching?`${T.search(n)} ${T.query} «${raw}»`:T.results(n);status.classList.toggle('is-searching',isSearching)}if(clear)clear.hidden=!isSearching;}
filters.addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(!b)return;setActive(b.dataset.filter);apply()});
let timer;search.addEventListener('input',()=>{if(search.value.trim())setActive('all');clearTimeout(timer);timer=setTimeout(apply,80)});search.addEventListener('search',apply);
clear?.addEventListener('click',()=>{search.value='';setActive('all');document.querySelectorAll('.faq-item').forEach(el=>el.open=false);apply();search.focus()});
document.addEventListener('click',async e=>{const b=e.target.closest('.copy-link');if(!b)return;const u=new URL(location.href);u.hash=b.dataset.copyId;try{await navigator.clipboard.writeText(u);b.textContent=T.copied;b.classList.add('copied');setTimeout(()=>{b.textContent=T.copy;b.classList.remove('copied')},1800)}catch{location.hash=b.dataset.copyId}});
if(location.hash){requestAnimationFrame(()=>{const t=document.querySelector(location.hash);if(t?.matches('details'))t.open=true;t?.scrollIntoView({block:'start'})})}
document.getElementById('back-top')?.addEventListener('click',e=>{e.preventDefault();scrollTo({top:0,behavior:'smooth'})});
apply();
const base=lang==='en'?'https://matveyshemyakin.ru/en/patients/':'https://matveyshemyakin.ru/patients/';const schema={'@context':'https://schema.org','@type':'FAQPage','@id':base+'#faq',url:base,name:lang==='en'?'Patient information — cataract surgery FAQs':'Пациентам — частые вопросы об операции по поводу катаракты',inLanguage:lang,lastReviewed:'2026-07-20',reviewedBy:{'@type':'Person','@id':'https://matveyshemyakin.ru/#person',name:lang==='en'?'Matvey Yuryevich Shemyakin':'Матвей Юрьевич Шемякин',jobTitle:lang==='en'?'Ophthalmologist and ophthalmic surgeon':'Врач-офтальмолог, офтальмохирург',url:'https://matveyshemyakin.ru/'},mainEntity:DATA.faqs.map(f=>({'@type':'Question',name:f.q,acceptedAnswer:{'@type':'Answer',text:[f.short,...f.paragraphs,...f.important].join(' ')}}))};const tag=document.createElement('script');tag.type='application/ld+json';tag.text=JSON.stringify(schema);document.head.append(tag);
})();