(function(){
const responsiveStyle=document.createElement('style');responsiveStyle.textContent='@media(max-width:1160px){.patient-header nav{display:none}}';document.head.append(responsiveStyle);
const DATA=window.PATIENT_FAQ_DATA||{categories:[],faqs:[]},VIDEOS=window.PATIENT_VIDEOS||{};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const path=document.getElementById('path-grid'),filters=document.getElementById('filter-row'),groups=document.getElementById('faq-groups'),search=document.getElementById('faq-search'),empty=document.getElementById('search-empty');
function video(id){const v=VIDEOS[id];if(!v)return `<aside class="video-slot"><div class="video-placeholder"><span aria-hidden="true">▶</span><p>Видео готовится</p><small>После съёмки ролик появится здесь.</small></div></aside>`;if(v.kind==='youtube')return `<aside class="video-slot"><iframe src="${esc(v.src)}" title="${esc(v.title||'Видеоответ')}" loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></aside>`;return `<aside class="video-slot"><video controls playsinline preload="metadata" src="${esc(v.src)}"${v.poster?` poster="${esc(v.poster)}"`:''}></video></aside>`}
function item(f){const ps=f.paragraphs.map(p=>`<p>${esc(p)}</p>`).join(''),li=f.important.map(x=>`<li>${esc(x)}</li>`).join(''),index=(f.q+' '+f.short+' '+f.paragraphs.join(' ')).toLowerCase();return `<details class="faq-item" id="${esc(f.id)}" data-category="${esc(f.cat)}" data-search="${esc(index)}"><summary><span class="faq-question">${esc(f.q)}</span><span class="faq-toggle" aria-hidden="true">+</span></summary><div class="faq-content"><div class="answer-copy"><p class="short-answer"><span>Короткий ответ</span>${esc(f.short)}</p><div class="answer-detail"><h4>Подробнее</h4>${ps}</div><div class="answer-important"><h4>Что важно</h4><ul>${li}</ul></div><div class="answer-meta"><span>Медицинская проверка: 19.07.2026</span><button class="copy-link" type="button" data-copy-id="${esc(f.id)}">Скопировать ссылку</button></div></div>${video(f.id)}</div></details>`}
path.innerHTML=DATA.categories.map(c=>`<a class="path-card" href="#section-${c.key}"><span>${c.number}</span><h3>${esc(c.title)}</h3><p>${esc(c.description)}</p><strong>${DATA.faqs.filter(f=>f.cat===c.key).length} вопросов →</strong></a>`).join('');
filters.innerHTML=`<button class="filter-button active" type="button" data-filter="all">Все вопросы</button>`+DATA.categories.map(c=>`<button class="filter-button" type="button" data-filter="${c.key}">${esc(c.title)}</button>`).join('');
groups.innerHTML=DATA.categories.map(c=>`<section class="faq-group" id="section-${c.key}" data-category-section="${c.key}"><div class="faq-group-head"><span>${c.number}</span><div><p>${esc(c.description)}</p><h2>${esc(c.title)}</h2></div></div><div class="faq-list">${DATA.faqs.filter(f=>f.cat===c.key).map(item).join('')}</div></section>`).join('');
let active='all';const norm=v=>v.toLowerCase().replace(/ё/g,'е').trim();function apply(){const term=norm(search.value||'');let n=0;document.querySelectorAll('.faq-item').forEach(el=>{const show=(active==='all'||el.dataset.category===active)&&(!term||norm(el.dataset.search).includes(term));el.hidden=!show;if(show)n++});document.querySelectorAll('.faq-group').forEach(g=>g.hidden=![...g.querySelectorAll('.faq-item')].some(x=>!x.hidden));empty.hidden=n!==0}filters.addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(!b)return;filters.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active');active=b.dataset.filter;apply()});search.addEventListener('input',apply);
document.addEventListener('click',async e=>{const b=e.target.closest('.copy-link');if(!b)return;const u=new URL(location.href);u.hash=b.dataset.copyId;try{await navigator.clipboard.writeText(u);b.textContent='Ссылка скопирована';b.classList.add('copied');setTimeout(()=>{b.textContent='Скопировать ссылку';b.classList.remove('copied')},1800)}catch{location.hash=b.dataset.copyId}});
if(location.hash){requestAnimationFrame(()=>{const t=document.querySelector(location.hash);if(t?.matches('details'))t.open=true;t?.scrollIntoView({block:'start'})})}
document.getElementById('back-top')?.addEventListener('click',e=>{e.preventDefault();scrollTo({top:0,behavior:'smooth'})});
const schema={'@context':'https://schema.org','@type':'FAQPage','@id':'https://matveyshemyakin.ru/patients/#faq',url:'https://matveyshemyakin.ru/patients/',name:'Пациентам — частые вопросы об операциях на глазах',inLanguage:'ru',lastReviewed:'2026-07-19',reviewedBy:{'@type':'Person','@id':'https://matveyshemyakin.ru/#person',name:'Матвей Юрьевич Шемякин',jobTitle:'Врач-офтальмолог, офтальмохирург',url:'https://matveyshemyakin.ru/'},mainEntity:DATA.faqs.map(f=>({'@type':'Question',name:f.q,acceptedAnswer:{'@type':'Answer',text:[f.short,...f.paragraphs,...f.important].join(' ')}}))};const tag=document.createElement('script');tag.type='application/ld+json';tag.text=JSON.stringify(schema);document.head.append(tag);
})();